spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database:  fitnessactivity

server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
    registerWithEureka: true
    fetchRegistry: true